---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - git
    - python-virtualenv
    - sudo

- name: ensure sudo keeps SSH_AUTH_SOCK in environment
  copy: src=env
        dest=/etc/sudoers.d/env
        mode=0440
        owner=root
        group=root

- name: add host key for github.com
  copy: src=ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        mode=0644
        owner=root
        group=root

- name: clone repo from github
  git: repo=https://github.com/mpolden/jarvis2.git
       dest={{ app_path }}
  notify:
    - restart uwsgi

- name: install pip in virtualenv
  pip: name=pip
       version=9.0.1
       virtualenv={{ app_path }}/venv

- name: install requirements in virtualenv
  pip: requirements={{ app_path }}/requirements.txt
       virtualenv={{ app_path }}/venv
  notify:
    - restart uwsgi

- name: copy config
  copy: src=../../../../jarvis/config.py
        dest={{ app_path }}/jarvis/config.py
        owner=root
        group=root
        mode=0644
  notify:
    - restart uwsgi

- name: copy google api credentials
  copy: src=../../../../jarvis/jobs/{{ item }}
        dest={{ app_path }}/jarvis/jobs/{{ item }}
        owner=www-data
        group=www-data
        mode=0600
  ignore_errors: yes
  with_items: "{{ google_credentials_files }}"
  notify:
    - restart uwsgi

- name: create generated directories
  file: >
        path={{ app_path }}/jarvis/static/{{ item }}
        owner=www-data
        group=www-data
        mode=0755
        state=directory
  with_items:
    - gen
    - .webassets-cache
